# 随机变量 {#chp02}

## 随机变量

随机变量：定义在样本空间上的实值函数

## 离散随机变量

### 概率质量函数 (pmf)

- 用 $p(a) = P\{X=a\}$ 定义
- $p(a)$ 最多在可数个 $a$ 上的值是正的

### 累积分布函数（cdf）

- $F(a) = \sum_{x_i\leq a} P\{x_i\}$
- 累积分布函数的函数图像

### 常用离散随机变量

- 伯努利随机变量 $$p(0)=1-p, p(1)=p$$
- 二项随机变量 $$p(i) = \binom{n}{i}p^i(1-p)^{n-i}, i=0,1,\cdots,n$$
- 几何随机变量 $$p(n) = (1-p)^{n-1}p, i=1,2,\cdots$$
- 泊松随机变量 $$p(i)=e^{-\lambda}\frac{\lambda^{i}}{i!}, i=1,2,\cdots$$

## 连续随机变量

**概率密度函数** (Probability density function)

- 称非负函数 $f(x)$ 为密度函数，如果对任意的实数集 $B$，有

$$F(x) = \int_Bf(x)dx.$$

- 密度函数决定了随机变量在任意实数集上的概率

- 学会用软件查看概率密度函数（pdf）的图像

### 常用连续随机变量

- 均匀随机变量 $$f(x)=\frac{1}{b-a}, a\leq x\leq b.$$
- 指数随机变量 $$f(x)=\lambda e^{-\lambda x}, x\geq 0.$$
- 伽马随机变量 $$f(x)=\frac{\lambda e^{-\lambda x}(\lambda x)^{\alpha-1}}{\Gamma(\alpha)}, x\geq 0.$$
- 正态随机变量 $$f(x)=\frac{1}{\sqrt{2\pi\sigma}}e^{-(x-\mu)^2/2\sigma^2}, -\infty \leq x \leq \infty$$

\clearpage

## 随机变量的期望

### 离散

- 伯努利随机变量的期望

- 二项式随机变量的期望

- 几何随机变量的期望

- 泊松随机变量的期望

### 连续

- 均匀随机变量的期望

- 指数随机变量的期望

- 正态随机变量的期望

- 计算以上三个随机变量的期望

### 随机变量的函数的期望、方差

- 如果 $X$ 离散 $$E[g(x)]=\sum_{x:p(x)>0}g(x)p(x)$$

- 如果 $X$ 连续 $$E[g(x)]=\int_{-\infty}^{\infty}g(x)f(x)dx$$

\clearpage

## 联合分布的随机变量

- 联合累积分布函数

- 联合概率质量函数（离散）

- 联合概率密度函数（连续）

- 随机变量的函数的联合分布密度

### 独立随机变量

### 协方差

## 矩母函数 $E[e^{tx}]$

- 离散随机变量 $$\sum_xe^{tx}p(x)$$

- 连续随机变量 \[\int_{-\infty}^{\infty}e^{tx}f(x)dx\]

**练习**：回忆第一讲里的 <a href="http://students.brown.edu/seeing-theory/statistical-inference/index.html#first" target="_blank">随机落点</a>，用概率空间和随机变量刻画这个问题，写出随机变量的概率密度函数，计算概率，并用大数定律来证明估计（estimator）收敛于 $\pi$.

## 发生事件数的分布 (略过)

\clearpage

## 极限定理

### 大数定律

假定 $X_1, X_2, \cdots$, 是一列独立同分布的随机变量，令 $E[X_i]=\mu$. 那么，当 $n\rightarrow\infty$ 时以概率 $1$ 有

$$\frac{X_1+X_2+\cdots+X_n}{n}\rightarrow\mu.$$

### 中心极限定理

假定 $X_1, X_2, \cdots$, 是一列独立同分布的随机变量，每个具有均值 $\mu$ 和方差 $\sigma^2$. 那么，当 $n\rightarrow\infty$ 时

$$\frac{X_1+X_2+\cdots+X_n-n\mu}{\sigma\sqrt{n}}$$
的分布趋于标准正态分布。

**练习**：请阐述证明这个定理的基本思路。

\clearpage

## 随机过程

### 随机过程的定义
- 随机过程是随机变量的一个集合，表示为

$$\{X(t),t\in T\}$$

- $X(t)$ 表示过程在时间 $t$ 的状态

- $T$ 表示过程的指标集； $T$ 为可数（不可数）集时称为离散（连续）过程

- 状态空间定义为 $X(t)$ 所有可能的取值范围

### 一个随机过程的示例
考察一个粒子沿圆周以 $0,1,\cdots,m$ 标志的 $m+1$ 个顶点的一个集合移动。
粒子每一步都等可能地沿顺时针方向或逆时针方向移动一个位置。
也就是说， $X_n$ 是粒子在第 $n$ 步后的位置，那么

$$P\{X_{n+1}=i+1|X_n=i\}=P\{X_{n+1}=i-1|X_n=i\}=\frac{1}{2}.$$
其中当 $i=m$ 时 $i+1:=0$, 而当 $i=0$ 时 $i-1:=m$.
假设现在粒子在 0 出发，而且持续地按上面的规律移动，直至所有顶点  $1,\cdots,m$ 都访遍。
问顶点  $i(1,\cdots,m)$ 是最后访问的概率是多少？
