# 马尔可夫链 {#chp04}

## 引言

复习：随机过程、指标集、状态的定义分别是什么？

我们通过几个马尔可夫链的例子，引入马尔可夫链的定义。

**例 4.1** (天气预报)

假设明天下雨的机会只依赖于前一天的天气条件，即今天是否下雨，而不依赖过去的天气条件。再假设如果今天下雨，那么明天下雨的概率为 $\alpha$; 如果今天没有下雨，那么明天下雨的概率为 $\beta$.

**思考**：怎样来描述这个随机过程？

**例 4.4** (将一个过程转变为马尔可夫链)

假设今天是否下雨依赖于前两天的天气条件。特别地，假设如果过去的两天都下雨，那么明天下雨的概率为 0.7; 如果今天下雨，但昨天没有下雨，那么明天下雨的概率为 0.5；如果昨天下雨，但今天没有下雨，那么明天下雨的概率为 0.4；如果过去的两天都没有下雨，那么明天下雨的概率为0.2.

怎样来描述这个随机过程？

**例 4.6** (赌博模型)

考察一个赌徒，在每局中赢 1 元的概率为 $p$，输 1 元的概率为 $1-p$.
如果我们假设他在破产时或者在财富达到 $N$ 元时离开。  

**问题**：怎样来描述这个随机过程？

**马尔可夫链定义**

- 一个随机过程 $\{X(t),t\in T\}$

	- $T$ 是可数的

	- 状态空间是可数的

- 只要过程当前的状态为 $i$, 那么在下一个时刻进入状态 $j$ 的概率为一个固定的概率 $P_{ij}$. 即对于一切状态 $i_0,i_1,\cdots,i_{n-1},$ 有

\begin{equation*}
P\{X_{n+1}=j|X_n=i,X_{n-1}=i_{n-1},\cdots,X_1=i_1,X_0=i_0\}=P_{ij}.
\end{equation*}

**转移概率（Transition probability）**

$P_{ij} := P\{X_{n+1}=j|X_n=i\}$ 表示过程处在状态 $i$ 时下一步转移到状态 $j$ 的概率。

**问题**： $\{P_{ij},j=0,1,\cdots\}$ 必须满足什么条件？

\clearpage

## $C$ - $K$ 方程

**$l$ 步转移概率**

前面我们已经定义了一步转移概率 $P_{ij}$，现在我们定义 $l$ 步转移概率——即处于状态 $i$ 的过程将在 $l$ 次转移以后处于状态 $j$ 的概率

$$P_{ij}^l := P\{X_{l+k}=j|X_k=i\}.$$

**问题**： 当 $l = n+m$ 时，怎么计算 $P_{ij}^l$? 

试证明以下公式：

- $$P_{ij}^l = \sum_{k=0}^{\infty}P_{ik}^nP_{kj}^m$$

- $$P^{(n+m)}=P^{(n)}P^{(m)}$$

- $$P^{(n)}=P^{n}$$

**例 4.8**

在例 4.1 中，天气是两个状态的马尔可夫链。如果 $\alpha=0.7$ 且 $\beta=0.4$，那么假定今天下雨，计算今天往后的第 4 天下雨的概率。

**例 4.10**

在瓮中总含有两个球。球的颜色有红色和蓝色。每个时期随机地取出一个球，并且放回一个新球，新球的颜色以 0.8 的概率与取得球同色，而以 0.2 的概率为相反的颜色。如果开始时两个球都是红色，求第五次取得的球是红色的概率。

\clearpage

## 状态的分类

状态 $j$ 称为是从状态 $i$ 可达的，如果对于某个 $n\geq 0$ 有 $P_{ij}^n>0$.

从 $i$ 可达 $j$, 当且仅当从 $i$ 开始的过程可能到达状态 $j$.

互相可达的两个状态 $i$ 和 $j$ 称为互通的，写为 $i \leftrightarrow j$.

- 互通的传递性
- 不可约的马尔可夫链

**常返态与暂态**

状态 $i$ 称为**常返态**，如果开始在状态 $i$ 的过程迟早要再进入 $i$ 的概率 $f_i$ 为 1. 如果 $f_i < 1$, 则称为暂态。

**命题 4.1** 状态 $i$ 是否常返由 $\sum_{n=1}^{\infty} P_{ii}^n$ 决定： 当其为无穷大时为常返态，否则为暂态。

$$f_{ij}:=P\{\exists\;n>0,\;X_n=j | X_0=i\}$$

**问题**：在什么条件下， $f_{ij}=1$?

**命题 4.3** 若 $i$ 是常返的，且 $i$ 和 $j$ 互通，则 $f_{ij}=1$.

\clearpage

## 长程性质和极限概率

返回时间及其期望值

对一个常返状态 $j$，考察从 $j$ 出发后返回状态 $j$ 的时间 $N_j$,

$$N_j := \min \{n>0 : X_n=j\}.$$
$$m_j := E[N_j|X_0=j].$$

**定义** 若 $m_j<\infty$, 则称状态 $j$ 为正常返的，而若 $m_j=\infty$, 则称状态 $j$ 为零常返的。


马尔可夫链停留在状态 $j$ 的比例 $\pi_j$

**思考**: $\pi_j$ 和什么密切相关？

**命题 4.4** 若马尔可夫链是不可约且常返的

$$\pi_j = \frac{1}{m_j}.$$

状态的**进一步**分类：正常返

**回顾**: 在本节之前，我们曾经做过什么样的分类？

**命题 4.5** 若 $i$ 是正常返的，且 $i \leftrightarrow j$，则 $j$ 是正常返的。


求解**不可约**马尔可夫链的长程时间比例

**思考**: $\pi_j$ 应该满足什么条件？


**定理 4.4** 考虑一个不可约的马尔可夫链。若此链是正常返的，则长程比例是下面方程组的唯一解

$$\pi_j=\sum_i\pi_ip_{ij},j\geq1$$
$$\sum_j\pi_j=1$$

**思考**: 如果方程组无解，我们能得到什么结果？

如上述方程组无解，则此马尔可夫链是暂态的或者是零常返的。

**例 4.22** 社会学家感兴趣的一个问题是确定高职业阶层或较低职业阶层在社会中的比例。一个可能的数学模型是，假定讲一个家庭中相继的后代在社会职业阶层之间的转移看成像马尔科夫链那样地转移。即一个孩子的职业只决定于他父母的职业。假定这个模型是恰当的，并且转移矩阵为
$$
\begin{bmatrix}
0.45 & 0.48 & 0.07 \\
0.05 & 0.70 & 0.25 \\
0.01 & 0.50 & 0.49 \\
\end{bmatrix}
$$

\clearpage

## 一些应用

**4.5.2 线性规划的算法复杂性**： 在条件 $Ax=b,x\geq 0$ 下，最小化 $cx$. 其中 $A$ 是一个固定常数的 $m\times n$ 矩阵， $c=(c_1,\cdots,c_n)$ 和 $b=(b_1,\cdots,b_m)$ 是固定常数的向量，而 $x=(x_1,\cdots,x_n)$ 是非负值的 $n$ 维向量。假设 $n>m$, 可以证明总能选取到至少有 $n-m$ 分量为 0 的最优值 $x$, 即它总可以取成可行域中的一个所谓极值点。

**思考:** 单纯性法解线性规划是通过可行域的一个极值点向一个更好的极值点移动直至得到最优点。因为这样的极值点可能有 $\binom{n}{m}$ 个，这个方法看起来需要很多次的迭代，事实上是这样吗？


## 在暂态停留的平均时间

略过

## 分支过程

略过

## 时间可逆的马尔可夫链
考察一个具有转移概率 $P_{ij}$ 和平稳概率 $\pi_i$ 的遍历马尔可夫链（即一个已经长时间运行的遍历的马尔可夫链），假设它开始于某个时间，我们沿时间的反向追踪其状态序列。这个状态序列本身也是一个马尔可夫链。

**思考:** 怎么证明其为马尔可夫链？从直观出发，怎么计算转移概率 $Q_{ij}$？

**定义:** 如果 $Q_{ij}=P_{ij}$, 则称这个马尔可夫链为**时间可逆**的。

$Q_{ij}=P_{ij}$ 也可以表示为 $\pi_iP_{ij}=\pi_jP_{ji}$. 我们称 $\pi_iP_{ij}$ 为从 $i$ 到 $j$ 的**转移率**

\clearpage

## 马尔可夫链蒙特卡罗方法

令 $X$ 是一个离散的随即向量，它的可能值的集合是 $x_j$, $j\geq1$. 令 $X$ 的概率质量函数为 $P\{X=x_j\}$, $j\geq1$，而且假设我们想对某些特殊的函数 $h$ 计算

$$\theta = E[h(X)] = \sum_{j=1}^\infty h(x_j)P\{X=x_j\}$$

在求函数的值在计算上有困难的情形，我们常常转为用模拟近似 $\theta$.
这种方法，称为 **蒙特卡罗方法**。

然而，常常很难生成具有特定的概率质量函数的随机向量。这种情况下，生成一个以 $P\{X=x_j\} (j\geq1)$ 为平稳概率的马尔可夫链 $X_1, X_2, \ldots$, 用 $h(X_i)$ 的平均值作为估计量去估计 $\theta$.

**例 4.39** 对于给定的常数 $a$, 令集合 $\mathcal{S}$ 为所有满足 $\sum_{j=1}^n jx_j > a$ 的 $(x_1, \ldots, x_n)$, 其中  $(x_1, \ldots, x_n)$ 为 $(1, \ldots, n)$ 的任一个排列 (permutation). 如果从 $\mathcal{S}$ 上的均匀分布中采样，请问该怎么做？

**思考:** 能算出 $\mathcal{S}$ 中有多少个元素吗？

我们可以考虑用**黑斯廷斯-梅特罗波利斯**算法来完成这个任务。

\clearpage

**黑斯廷斯-梅特罗波利斯 算法**

**算法目的**
设 $\boldsymbol{\varphi}$ 为可数的正整数集合。
当 $\boldsymbol{\varphi}$ 有限时，其为 $\{1,2,\cdots,N\}$, 当 $\boldsymbol{\varphi}$ 无限时，其为 $\{1,2,\dots\}$.

给定
$$\left\{b_j,j\in \boldsymbol{\varphi} \; \mid \; \sum b_j=B < \infty \right\},$$
我们希望生成一个具有平稳概率

$$\left\{\pi_j=\frac{b(j)}{B},j\in \boldsymbol{\varphi}\right\}$$
的时间可逆的马尔可夫链，使其平稳概率等于给定平稳概率。

<!-- Test \middle https://app.yinxiang.com/shard/s22/nl/4928451/4b389533-22a0-45cb-a533-ea0d91be90fe/
$$\left( a \middle b \right)$$ -->

**算法步骤**

1. 选取一个状态空间为 $\boldsymbol{\varphi}$ 的不可约马尔可夫转移概率矩阵 $Q$, 以 $q(i,j)$ 表示此矩阵的第 $i$ 行 $j$ 列的元素;
2. 设 $X_n=i,\;i=0,1,\cdots$, 其中 $X_0$ 为起始状态，可以任意选取;
3. 生成 ^[即从分布采样。]一个随机变量 $Y_i$, 概率分布满足 $P\{Y_i=k\}=q(i,k), k\in \boldsymbol{\varphi};$
4. 如果 $Y_i=i$, 则 $X_{n+1}=i$, 略过第 $5\sim 7$ 步，转到第 $8$ 步;
5. 如果 $Y_i=j, j\neq i$, 比较 $\pi(j)q(j,i)$ 和 $\pi(i)q(i,j)$ 的大小。
    1. 如果 $\pi(j)q(j,i)\geq\pi(i)q(i,j)$, 则 $X_{n+1}=j$, 略过第 $6$ 和 $7$ 步，转到第 $8$ 步;
    2. 如果 $\pi(j)q(j,i) < \pi(i)q(i,j)$, 则 $X_{n+1}$ 可能为 $j$ 或者 $i$，进入第 $6$ 步。
6. 生成一个随机变量 $Z$, $Z \sim U[0,1]$. ^[即从 $0$ 到 $1$ 的一致分布(Uniform distribution).]
7. 如果 $$Z<\frac{\pi(j)q(j,i)}{\pi(i)q(i,j)},$$ 则 $X_{n+1}=j$, 否则 $X_{n+1}=i$.
<!-- $X_{n+1}$ 为 $j$ 的概率为 $$\frac{\pi(j)q(j,i)}{\pi(i)q(i,j)},$$
$X_{n+1}$ 为 $i$ 的概率为 $$1-\frac{\pi(j)q(j,i)}{\pi(i)q(i,j)};$$ -->
8. 重复 $2\sim 7$ 的步骤生成一个马尔可夫链。

\clearpage

## 马尔可夫决策过程

状态空间为 $\{1,\cdots,M\}$; $A:=$所有可能的动作的集合

$P_{ij}(a):=P\{X_{n+1}=j|X_n=i,a_n=a,\cdots,X_1,a_1,X_0,a_0\}$

$\beta:=\{\beta_i(a), a\in A, i=1,\cdots,M\}$

在任意给定的策略 $\beta$ 下，状态序列 $\{X_n,n=0,1,2,\cdots\}$ 构成一个马尔可夫链，其转移概率为 $$P_{ij}(\beta)=P_{\beta}\{X_{n+1}=j|X_n=i\}=\sum_aP_{ij}(a)\beta_i(a)$$

## 隐马尔可夫链
**例 4.42** 考虑一个生产过程，在每个时段它或者处在一个好的状态（状态1），或者处在一个差的状态（状态2）。如果在一个时段过程处在状态1，独立于过去，在下一个时段将以概率0.9处在状态1，概率0.1处在状态2。一旦状态处在状态2，它将永远处在状态2。假设每个时段生产一个产品，当过程处在状态1时，每个生产的产品以概率0.99达到可接受的质量，而当过程处在状态2时，生产的产品以概率0.96达到可接受的质量。

如果每个产品的状况相继地被观测到，而过程的状态不能观测到，那么这是一个隐马尔科夫链模型。

